### ISSUE TITLE
PHP 7.2 - Cannot use 'Object' as class name as it is reserved

### ISSUE THREAD

**Issue by 0xRomain** [wonderpush/wonderpush-php-lib#1]
**Description**

PHP 7.2 uses "Object" as typehint (https://wiki.php.net/rfc/object-typehint).

**Comment by mickaelwegerich** [comment]
+1 with PHP 7.3

**Comment by cocktailkrabbe** [comment]
+1

**Comment by ofavre** [comment]
This is fixed with the v2.0.0 that has just been released!
