### ISSUE TITLE
Using composer on Laravel 5.3 I get error

### ISSUE THREAD

**Issue by giojkd** [wonderpush/wonderpush-php-lib#2]
Carbon 1 is deprecated, see how to migrate to Carbon 2, how to fix it ?

**Comment by ofavre** [comment]
Can you try wit hthe v2.0.0 that we've just released?
If you still have an error can you please post it so that I know where to search?
We have no dependencies so I think, that the issue lies on your project and is not related to this library.

**Comment by ofavre** [comment]
Closing stale issue.
