### ISSUE TITLE
What date format to use with setDeliveryDate() ?

### ISSUE THREAD

**Issue by jfadev** [wonderpush/wonderpush-php-lib#4]
Hello, I would like to know in what date format should be placed in the `setDeliveryDate()` method?

```
$deliveries = DeliveriesCreateParams::_new()->setNotification($notification);
$deliveries->setDeliveryDate($deliveryDate);
```
In the documentation it only says that it is of type `string`:
`setDeliveryDate( string $deliveryDate ) : WonderPush\Params\DeliveriesCreateParams`

I've never gotten this to work.

I am looking forward to your response.
Thank you so much!

**Comment by ofavre** [comment]
Hi,

The [format for dates](https://docs.wonderpush.com/reference/conventions#dates-and-times) is described in the [Conventions](https://docs.wonderpush.com/reference/conventions) section of our API reference:

> WonderPush exclusively uses UNIX timestamps *in milliseconds* (time elapsed since January 1st 1970), and expresses textual dates and times in UTC, always specifying the used timezone to avoid confusion.
> You can also use a textual representation of a date using the following ISO8601 format: `YYYY[-MM[-DD]][T[HH[:MM[:SS[.SSS]]]][Z|+HH[:MM[:SS[.SSS]]]]]`
> Here are valid examples: `2015`, `2015-12`, `2015-12-31`, `2015-12-31T23`, `2015-12-31T23:59`, `2015-12-31T23:59:59`, `2015-12-31T23:59:59.999`.
> Here are valid offsets you can also append: `Z` for UTC, `-06`, `+02:00`. In the absence of an offset, the date is taken as UTC. Don't forget to write `T` before the offset if you gave no time-part.
> Unless explicitly mentioned, any missing part is taken as January 1st for date-part and midnight for the time-part.
> 
> Any field or parameter that ends with `Date` expects a UNIX timestamp in millisecond as an integer, or an ISO8601 formatted string.
